name: Build Release
env:
  DOWNLOAD_CACHE_VERSION: '8'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHONPATH: .

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  osxbuild:
    name: Build on MacOS
    runs-on: macos-15
    timeout-minutes: 60
    steps:
      - name: Clone LLVM and AMD projects
        run: |
            mkdir -p ${{ github.workspace }}/llvm-project/amd/comgr/build/
            echo x > libamd_comgr.dylib
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v6.1.0
          release_name: Build v6.1.0
          draft: false
          prerelease: false
      - name: Upload libamd_comgr.dylib to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/llvm-project/amd/comgr/build/libamd_comgr.dylib
          asset_name: libamd_comgr.dylib
          asset_content_type: application/octet-stream
