name: Build Release
env:
  DOWNLOAD_CACHE_VERSION: '8'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PYTHONPATH: .

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  osxbuild:
    name: Build on MacOS
    runs-on: macos-15
    permissions:
      contents: write
    timeout-minutes: 60
    steps:
      - name: Clone LLVM and AMD projects
        run: |
            mkdir -p ${{ github.workspace }}/llvm-project/amd/comgr/build/
            echo x > libamd_comgr.dylib
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/llvm-project/amd/comgr/build/libamd_comgr.dylib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
